# Generated by Django 5.2.7 on 2025-11-04 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=120)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(max_length=34)),
                ('ifsc', models.CharField(max_length=11)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('upi_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
