# Generated by Django 5.2.7 on 2025-11-04 09:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bankaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
