# Generated by Django 5.2.7 on 2025-11-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bankaccount_amount'),
        ('api', '0005_create_transaction_model'),
    ]

    operations = [
    ]
