# Generated by Django 5.2.7 on 2025-11-05 17:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transaction_receiver_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('postpaid', 'Postpaid Mobile'), ('dth', 'DTH'), ('broadband', 'Broadband'), ('gas', 'Gas')], max_length=32)),
                ('logo', models.URLField(blank=True, null=True)),
                ('circle', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_number', models.CharField(max_length=128)),
                ('name_on_bill', models.CharField(blank=True, max_length=128, null=True)),
                ('period', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('provider_txn', models.CharField(blank=True, max_length=128, null=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.biller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
       
    ]
